# Generated by Django 5.0.6 on 2026-06-14 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0002_carrera_facultad_tipousuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='qr_expiracion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='qr_tipo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='qr_token',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
    ]
