# Generated by Django 5.0.6 on 2026-06-15 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0005_sesionusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='chromebook',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='chromebooks/', verbose_name='Foto del equipo'),
        ),
        migrations.AlterField(
            model_name='chromebook',
            name='condicion',
            field=models.CharField(choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo')], default='bueno', max_length=20),
        ),
    ]
