# Generated by Django 5.0.6 on 2026-06-18 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0007_usuario_origen_matricula_id_sincronizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='en_garantia',
            field=models.BooleanField(default=False, verbose_name='¿En garantía?'),
        ),
    ]
