# Generated by Django 5.0.6 on 2026-06-19 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0008_mantenimiento_en_garantia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chromebook',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('prestado', 'Prestado'), ('reservado', 'Reservado'), ('mantenimiento', 'Mantenimiento')], default='disponible', max_length=20),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='estado',
            field=models.CharField(choices=[('reservado', 'Reservado'), ('activo', 'Activo'), ('devuelto', 'Devuelto'), ('vencido', 'Vencido')], default='activo', max_length=20),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_prestamo',
            field=models.DateTimeField(),
        ),
    ]
