# Generated by Django 5.0.6 on 2026-06-20 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0009_alter_chromebook_estado_alter_prestamo_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada'), ('vencida', 'Vencida')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
    ]
