# Generated by Django 5.0.6 on 2026-06-21 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0010_alter_reserva_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/', verbose_name='Foto de perfil'),
        ),
    ]
