# Generated by Django 5.0.6 on 2026-06-21 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0011_usuario_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_matriculas_activa', models.BooleanField(default=True, verbose_name='Conexión con API de Matrículas activa')),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuración del Sistema',
                'db_table': 'tb_configuracion_sistema',
            },
        ),
    ]
