# Generated by Django 5.0.6 on 2026-06-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0014_usuario_control_acceso'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='bloqueado',
            field=models.BooleanField(default=False, verbose_name='Bloqueado remotamente'),
        ),
    ]
