# Generated by Django 5.0.6 on 2026-06-28 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0015_prestamo_bloqueado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='chromebook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='prestamos.chromebook', verbose_name='Chromebook asignado'),
        ),
    ]
