# Generated by Django 5.0.6 on 2026-06-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0016_reserva_chromebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='chromebook',
            name='ultimo_heartbeat',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última conexión del kiosko'),
        ),
    ]
