# Generated by Django 5.0.6 on 2026-06-30 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0017_chromebook_ultimo_heartbeat'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chromebook',
            table='tb_chromebook',
        ),
        migrations.AlterModelTable(
            name='prestamo',
            table='tb_prestamo',
        ),
    ]
