# Generated by Django 5.0.6 on 2026-07-05 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0018_alter_chromebook_table_alter_prestamo_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Técnico',
                'verbose_name_plural': 'Técnicos',
                'db_table': 'tb_tecnico',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='tecnico_asignado',
            field=models.ForeignKey(blank=True, help_text='Técnico de TICs responsable (el campo "tecnico" guarda el nombre por compatibilidad).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos', to='prestamos.tecnico'),
        ),
    ]
