# Generated by Django 5.0.6 on 2026-07-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0019_tecnico_mantenimiento_tecnico_asignado'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='evidencia_reparacion',
            field=models.FileField(blank=True, null=True, upload_to='mantenimiento_evidencias/'),
        ),
    ]
