# Generated by Django 5.0.6 on 2026-07-07 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0020_mantenimiento_evidencia_reparacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='confirmado_por_tecnico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='fecha_confirmacion_tecnico',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
