# Generated by Django 5.0.6 on 2026-07-11 20:27

import apps.prestamos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0021_mantenimiento_confirmado_por_tecnico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chromebook',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=apps.prestamos.models._foto_chromebook_path, verbose_name='Foto del equipo'),
        ),
    ]
