# Generated by Django 5.0.6 on 2026-07-13 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0022_alter_chromebook_foto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudAsesoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('canal', models.CharField(choices=[('web', 'Web'), ('whatsapp', 'WhatsApp')], default='web', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('nombre', models.CharField(blank=True, max_length=150)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('activa', 'Activa'), ('cerrada', 'Cerrada')], default='pendiente', max_length=20)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asesorias', to='prestamos.estudiante')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asesorias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de asesoría',
                'verbose_name_plural': 'Solicitudes de asesoría',
                'db_table': 'tb_solicitud_asesoria',
                'ordering': ['-actualizada'],
            },
        ),
        migrations.CreateModel(
            name='MensajeAsesoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remitente', models.CharField(choices=[('estudiante', 'Estudiante'), ('asesor', 'Asesor')], max_length=15)),
                ('texto', models.TextField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='prestamos.solicitudasesoria')),
            ],
            options={
                'verbose_name': 'Mensaje de asesoría',
                'verbose_name_plural': 'Mensajes de asesoría',
                'db_table': 'tb_mensaje_asesoria',
                'ordering': ['creado'],
            },
        ),
    ]
