# Generated by Django 5.0.6 on 2026-06-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiantematricula',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Teléfono'),
        ),
    ]
