"""
Django settings for proyecto_crai project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carga variables de entorno desde un archivo .env en la raíz del proyecto.
# El .env NO se versiona (ver .gitignore); usar .env.example como plantilla.
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Se lee exclusivamente del entorno (.env). No debe haber un valor por defecto
# versionado: cualquier clave en el repositorio queda comprometida.
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    raise RuntimeError('Falta SECRET_KEY: defínela en el archivo .env (ver .env.example).')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['immunize-bronco-graveyard.ngrok-free.dev', '127.0.0.1', 'localhost', '192.168.100.7', '.devtunnels.ms']

CSRF_TRUSTED_ORIGINS = [
    'https://immunize-bronco-graveyard.ngrok-free.dev',
    'http://immunize-bronco-graveyard.ngrok-free.dev',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.autenticacion.apps.AutenticacionConfig',
    'apps.prestamos.apps.PrestamosConfig',
    'apps.estudiantes.apps.EstudiantesConfig',  
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'apps.prestamos.middleware.SesionUnicaMiddleware',
    'apps.prestamos.middleware.RegistrarSesionMiddleware',
]

ROOT_URLCONF = 'proyecto_crai.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.prestamos.context_processors.usuario_context', 
            ],
        },
    },
]

WSGI_APPLICATION = 'proyecto_crai.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# Los datos de conexión se leen del .env para que el proyecto sea portable
# (cada equipo puede tener su propia contraseña de PostgreSQL). Los valores por
# defecto corresponden a la configuración de desarrollo original.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'crai_unemi'),
        'USER': os.environ.get('DB_USER', 'postgres'),
        'PASSWORD': os.environ.get('DB_PASSWORD', '1508'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'es-ec'

TIME_ZONE = 'America/Guayaquil'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',  # Esto usa Path
]



STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_URL = 'autenticacion:login'
LOGIN_REDIRECT_URL = 'prestamos:portal'
LOGOUT_REDIRECT_URL = 'autenticacion:login'




# ==================== CONFIGURACIÓN DE CORREO ====================
# Gmail SMTP para recuperación de contraseña

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')  # ← definir en .env
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')  # ← App Password de Gmail en .env
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'CRAI UNEMI <crai.unemi.test@gmail.com>')

# El enlace de recuperación/desbloqueo de contraseña caduca a los 5 minutos.
PASSWORD_RESET_TIMEOUT = 300  # segundos


# ==================== API EXTERNA DE MATRÍCULAS ====================
# Servicio que simula el sistema de matrículas de la UNEMI y es la fuente de
# verdad de los estudiantes. El sistema de reservas mantiene un espejo local.
API_MATRICULAS_BASE_URL = os.environ.get('API_MATRICULAS_BASE_URL', 'http://127.0.0.1:8001/api')
API_MATRICULAS_KEY = os.environ.get('API_MATRICULAS_KEY', 'clave-dev-compartida')  # debe coincidir con API_KEY_MATRICULAS de la API
API_MATRICULAS_TIMEOUT = float(os.environ.get('API_MATRICULAS_TIMEOUT', '5'))

# ==================== N8N CHATBOT ====================
# Webhook de n8n para procesar mensajes del chatbot
N8N_CHATBOT_WEBHOOK_URL = os.environ.get('N8N_CHATBOT_WEBHOOK_URL', 'http://localhost:5678/webhook/crai-chatbot')
N8N_API_KEY = os.environ.get('N8N_API_KEY', 'clave-n8n-dev')

# ==================== APP KIOSKO CHROMEBOOK ====================
# Clave compartida que la app instalada en cada Chromebook envía en el header
# 'X-KIOSKO-KEY' para consultar el estado/préstamo de su equipo.
KIOSKO_API_KEY = os.environ.get('KIOSKO_API_KEY', 'clave-kiosko-dev')

# ==================== WHATSAPP CLOUD API (Meta) ====================
# Webhook directo: Meta -> Django (sin n8n). Los valores reales van en .env.
WHATSAPP_VERIFY_TOKEN = os.environ.get('WHATSAPP_VERIFY_TOKEN', 'crai-verify-2026')
WHATSAPP_ACCESS_TOKEN = os.environ.get('WHATSAPP_ACCESS_TOKEN', '')  # token de Meta (caduca 24h el temporal)
WHATSAPP_PHONE_NUMBER_ID = os.environ.get('WHATSAPP_PHONE_NUMBER_ID', '1087899717740956')
WHATSAPP_API_VERSION = os.environ.get('WHATSAPP_API_VERSION', 'v21.0')
# ID de la app de Meta (para la subida de la foto de perfil del bot).
WHATSAPP_APP_ID = os.environ.get('WHATSAPP_APP_ID', '')
# Número visible del bot (formato internacional sin '+', ej. 15551234567) para
# el botón "Chatea por WhatsApp" del portal del estudiante (enlace wa.me).
WHATSAPP_NUMERO = os.environ.get('WHATSAPP_NUMERO', '')